# Nom du workflow
name: Mon Workflow

# Cette section définit les événements déclencheurs du workflow
on: 
  push:
    branches:
      - main

# Défini les jobs à exécuter dans le workflow
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation de la CLI Github
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg arch=all] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
          sudo apt update
          sudo apt install gh
      - name: Création de la pull Request
        run: |
          gh auth login --with-token < ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          gh pr create --base main --head ${{ github.ref }} --title "Nouvelle fonctionnalité" --body "Cette pull request ajoute une nouvelle fonctionnalité."

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installations des dépendances
        run: npm install
      - name: Exécution des tests
        run: npm test
      - name: Archivage des résultats de tests
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./reports/awesome-reports/
        env:
          ACTIONS_STEP_DEBUG: true
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Téléchargement des résultats de tests
        uses: actions/download-artifact@v2
        with:
          name: test-results
      - name: Déploiement sur le serveur de production
        run: |
          echo "Déploiement de l'application sur le serveur"
